openapi: 3.0.0
info:
  title: Proxy API
  description: API для получения и управления прокси-серверами
  version: 1.0.0

paths:
  /auth/register:
    post:
      $ref: './endpoints/auth.yaml#/register'
  /auth/login:
    post:
      $ref: './endpoints/auth.yaml#/login'
  /proxy:
    get:
      $ref: "./endpoints/proxy.yaml#/getProxies"
  /proxy/{id}:
    get:
      $ref: "./endpoints/proxy.yaml#/getProxyId"
